from __future__ import annotations

SOAP_ENVELOPE = """\
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" \
s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <s:Body>
        <u:X_SendIRCC xmlns:u="urn:schemas-sony-com:service:IRCC:1">
            <IRCCCode>{code}</IRCCCode>
        </u:X_SendIRCC>
    </s:Body>
</s:Envelope>"""

CODES: dict[str, str] = {
    "num0": "AAAAAQAAAAEAAAAJAw==",
    "num1": "AAAAAQAAAAEAAAAAAw==",
    "num2": "AAAAAQAAAAEAAAABAw==",
    "num3": "AAAAAQAAAAEAAAACAw==",
    "num4": "AAAAAQAAAAEAAAADAw==",
    "num5": "AAAAAQAAAAEAAAAEAw==",
    "num6": "AAAAAQAAAAEAAAAFAw==",
    "num7": "AAAAAQAAAAEAAAAGAw==",
    "num8": "AAAAAQAAAAEAAAAHAw==",
    "num9": "AAAAAQAAAAEAAAAIAw==",
    "num11": "AAAAAQAAAAEAAAAKAw==",
    "num12": "AAAAAQAAAAEAAAALAw==",
    "dot": "AAAAAgAAAJcAAAAdAw==",
    "tenkey": "AAAAAgAAAJcAAAAMAw==",
    "poweroff": "AAAAAQAAAAEAAAAvAw==",
    "sleep": "AAAAAQAAAAEAAAAvAw==",
    "wakeup": "AAAAAQAAAAEAAAAuAw==",
    "tvpower": "AAAAAQAAAAEAAAAVAw==",
    "volumeup": "AAAAAQAAAAEAAAASAw==",
    "volumedown": "AAAAAQAAAAEAAAATAw==",
    "mute": "AAAAAQAAAAEAAAAUAw==",
    "audio": "AAAAAQAAAAEAAAAXAw==",
    "audiomixup": "AAAAAgAAABoAAAA8Aw==",
    "audiomixdown": "AAAAAgAAABoAAAA9Aw==",
    "audiooutput": "AAAAAgAAAMQAAAAkAw==",
    "audiosystem": "AAAAAgAAAMQAAAAiAw==",
    "wirelesssubwoofer": "AAAAAgAAAMQAAAB+Aw==",
    "channelup": "AAAAAQAAAAEAAAAQAw==",
    "channeldown": "AAAAAQAAAAEAAAARAw==",
    "up": "AAAAAQAAAAEAAAB0Aw==",
    "down": "AAAAAQAAAAEAAAB1Aw==",
    "left": "AAAAAQAAAAEAAAA0Aw==",
    "right": "AAAAAQAAAAEAAAAzAw==",
    "confirm": "AAAAAQAAAAEAAABlAw==",
    "enter": "AAAAAQAAAAEAAAALAw==",
    "home": "AAAAAQAAAAEAAABgAw==",
    "back": "AAAAAgAAAJcAAAAjAw==",
    "return": "AAAAAgAAAJcAAAAjAw==",
    "exit": "AAAAAQAAAAEAAABjAw==",
    "options": "AAAAAgAAAJcAAAA2Aw==",
    "actionmenu": "AAAAAgAAAMQAAABLAw==",
    "topmenu": "AAAAAgAAABoAAABgAw==",
    "popupmenu": "AAAAAgAAABoAAABhAw==",
    "controlmenu": "AAAAAgAAABoAAAB1Aw==",
    "androidmenu": "AAAAAgAAAMQAAABPAw==",
    "dpadcenter": "AAAAAgAAAJcAAABKAw==",
    "cursorup": "AAAAAgAAAJcAAABPAw==",
    "cursordown": "AAAAAgAAAJcAAABQAw==",
    "cursorleft": "AAAAAgAAAJcAAABNAw==",
    "cursorright": "AAAAAgAAAJcAAABOAw==",
    "play": "AAAAAgAAAJcAAAAaAw==",
    "pause": "AAAAAgAAAJcAAAAZAw==",
    "playpause": "AAAAAgAAAJcAAAAPAw==",
    "stop": "AAAAAgAAAJcAAAAYAw==",
    "rewind": "AAAAAgAAAJcAAAAbAw==",
    "forward": "AAAAAgAAAJcAAAAcAw==",
    "prev": "AAAAAgAAAJcAAAA8Aw==",
    "next": "AAAAAgAAAJcAAAA9Aw==",
    "rec": "AAAAAgAAAJcAAAAgAw==",
    "input": "AAAAAQAAAAEAAAAlAw==",
    "tv": "AAAAAQAAAAEAAAAkAw==",
    "hdmi1": "AAAAAgAAABoAAABaAw==",
    "hdmi2": "AAAAAgAAABoAAABbAw==",
    "hdmi3": "AAAAAgAAABoAAABcAw==",
    "hdmi4": "AAAAAgAAABoAAABdAw==",
    "component1": "AAAAAgAAAKQAAAA2Aw==",
    "component2": "AAAAAgAAAKQAAAA3Aw==",
    "analog": "AAAAAgAAAHcAAAANAw==",
    "digital": "AAAAAgAAAJcAAAAyAw==",
    "digitaltoggle": "AAAAAgAAAHcAAABSAw==",
    "video1": "AAAAAQAAAAEAAABAAw==",
    "video2": "AAAAAQAAAAEAAABBAw==",
    "analogrgb1": "AAAAAQAAAAEAAABDAw==",
    "netflix": "AAAAAgAAABoAAAB8Aw==",
    "youtube": "AAAAAgAAAMQAAABHAw==",
    "googleplay": "AAAAAgAAAMQAAABGAw==",
    "featuredapp": "AAAAAgAAAMQAAABEAw==",
    "featuredappvod": "AAAAAgAAAMQAAABFAw==",
    "applauncher": "AAAAAgAAAMQAAAAqAw==",
    "googledashboard": "AAAAAgAAAMQAAABwAw==",
    "red": "AAAAAgAAAJcAAAAlAw==",
    "green": "AAAAAgAAAJcAAAAmAw==",
    "yellow": "AAAAAgAAAJcAAAAnAw==",
    "blue": "AAAAAgAAAJcAAAAkAw==",
    "guide": "AAAAAgAAAKQAAABbAw==",
    "epg": "AAAAAgAAAKQAAABbAw==",
    "display": "AAAAAQAAAAEAAAA6Aw==",
    "info": "AAAAAQAAAAEAAAA6Aw==",
    "help": "AAAAAgAAAMQAAABNAw==",
    "teletext": "AAAAAQAAAAEAAAA/Aw==",
    "subtitle": "AAAAAgAAAJcAAAAoAw==",
    "closedcaption": "AAAAAgAAAKQAAAAQAw==",
    "picturemode": "AAAAAQAAAAEAAABkAw==",
    "pictureoff": "AAAAAQAAAAEAAAA+Aw==",
    "wide": "AAAAAgAAAKQAAAA9Aw==",
    "mode3d": "AAAAAgAAAHcAAABNAw==",
    "gguide": "AAAAAQAAAAEAAAAOAw==",
    "tvantennacable": "AAAAAQAAAAEAAAAqAw==",
    "tvanalog": "AAAAAQAAAAEAAAA4Aw==",
    "tvsatellite": "AAAAAgAAAMQAAABOAw==",
    "bscs": "AAAAAgAAAJcAAAAQAw==",
    "bs": "AAAAAgAAAJcAAAAsAw==",
    "cs": "AAAAAgAAAJcAAAArAw==",
    "tvradio": "AAAAAgAAABoAAABXAw==",
    "ddata": "AAAAAgAAAJcAAAAVAw==",
    "advancedbscs": "AAAAAgAAAMQAAAAMAw==",
    "sleeptimer": "AAAAAQAAAAEAAAA2Aw==",
    "jump": "AAAAAQAAAAEAAAA7Aw==",
    "media": "AAAAAgAAAJcAAAA4Aw==",
    "syncmenu": "AAAAAgAAABoAAABYAw==",
    "footballmode": "AAAAAgAAABoAAAB2Aw==",
    "demomode": "AAAAAgAAAJcAAAB8Aw==",
    "demosurround": "AAAAAgAAAHcAAAB7Aw==",
    "pap": "AAAAAgAAAKQAAAB3Aw==",
    "flashplus": "AAAAAgAAAJcAAAB4Aw==",
    "flashminus": "AAAAAgAAAJcAAAB5Aw==",
    "photoframe": "AAAAAgAAABoAAABVAw==",
    "imanual": "AAAAAgAAABoAAAB7Aw==",
    "onetouchtimerec": "AAAAAgAAABoAAABkAw==",
    "onetouchview": "AAAAAgAAABoAAABlAw==",
    "assists": "AAAAAgAAAMQAAAA7Aw==",
    "acs": "AAAAAgAAAMQAAAArAw==",
    "recordermenu": "AAAAAgAAAMQAAABIAw==",
    "stbmenu": "AAAAAgAAAMQAAABJAw==",
    "darwinloop": "AAAAAgAAAMQAAAAlAw==",
    "partnerapp1": "AAAAAgAACB8AAAAAAw==",
    "partnerapp2": "AAAAAgAACB8AAAABAw==",
    "partnerapp3": "AAAAAgAACB8AAAACAw==",
    "partnerapp4": "AAAAAgAACB8AAAADAw==",
    "partnerapp5": "AAAAAgAACB8AAAAEAw==",
    "partnerapp6": "AAAAAgAACB8AAAAFAw==",
    "partnerapp7": "AAAAAgAACB8AAAAGAw==",
    "partnerapp8": "AAAAAgAACB8AAAAHAw==",
    "partnerapp9": "AAAAAgAACB8AAAAIAw==",
    "partnerapp10": "AAAAAgAACB8AAAAJAw==",
    "partnerapp11": "AAAAAgAACB8AAAAKAw==",
    "partnerapp12": "AAAAAgAACB8AAAALAw==",
    "partnerapp13": "AAAAAgAACB8AAAAMAw==",
    "partnerapp14": "AAAAAgAACB8AAAANAw==",
    "partnerapp15": "AAAAAgAACB8AAAAOAw==",
    "partnerapp16": "AAAAAgAACB8AAAAPAw==",
    "partnerapp17": "AAAAAgAACB8AAAAQAw==",
    "partnerapp18": "AAAAAgAACB8AAAARAw==",
    "partnerapp19": "AAAAAgAACB8AAAASAw==",
    "partnerapp20": "AAAAAgAACB8AAAATAw==",
}


def build_soap_body(ircc_code: str) -> str:
    return SOAP_ENVELOPE.format(code=ircc_code)


def get_code(name: str) -> str | None:
    return CODES.get(name.lower())


def list_keys() -> list[str]:
    return sorted(CODES.keys())
